version: '2'
services:
  tableagricole-app:
    image: tableagricole
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tableagricole-postgresql:5432/TableAgricole
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8089:8089
  tableagricole-postgresql:
    extends:
      file: postgresql.yml
      service: tableagricole-postgresql
