export const enum TypeBesoin {
  SURPLUSANNONCE = 'SURPLUSANNONCE',

  BESOINALIMENT = 'BESOINALIMENT',

  BESOINBENEVOLE = 'BESOINBENEVOLE',

  BESOINRH = 'BESOINRH',

  SURPLUSAGRI = 'SURPLUSAGRI',
}
